name: 'Pull Request Labeler'

on:
  # pull_request:
  #   types: [opened, ready_for_review, labeled, unlabeled, reopened, synchronize]
  pull_request_target:
    types: [opened, ready_for_review, labeled, unlabeled, reopened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.WORKFLOW_TOKEN }}"
