name: 'Pull Request Labeler'

on: [pull_request, pull_request_target]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.WORKFLOW_TOKEN }}"
